# version: '3.9'

# services:
#   metabase:
#     image: metabase/metabase:latest
#     container_name: metabase
#     hostname: metabase
#     volumes:
#       - data:/metabase
#     ports:
#       - 3000:3000
#     environment:
#       MB_DB_TYPE: postgres
#       MB_DB_DBNAME: metabase
#       MB_DB_PORT: 5431
#       MB_DB_USER: postgres
#       MB_DB_PASS: root
#       MB_DB_HOST: postgres
#     healthcheck:
#       test: curl --fail -I http://localhost:3000/api/health || exit 1
#       interval: 15s
#       timeout: 5s
#       retries: 5

#   postgres:
#     image: postgres:12-alpine
#     container_name: postgres_metabase
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: root
#       POSTGRES_DB: postgres
#     ports:
#       - '5431:5432'
#     restart: unless-stopped
#     volumes:
#       - ../datawarehouse/data:/var/lib/postgresql/data

# volumes:
#   data:

version: '3'
services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - data:/metabase

volumes:
  data:
