version: '3.9'
services:
  postgres:
    image: postgres:15.3
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: zini_system
    volumes:
      - ./data:/var/lib/postgresql/data
