version: '3'
services:
  database:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data

  app:
    build:
      context: .
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: root
      NEW_DB_NAME: newdatabase
    volumes:
      - ./script.py:/app/script.py
      - ./tables.sql:/app/tables.sql
