version: '3.5'

services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres_coki
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5431:5432'
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_coki
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - '8081:80'
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  data:
  pgadmin:
